[package]
name = "learn-rust-gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc_codegen_spirv = "*"
rustc_codegen_spirv-types = "*"
spirv-std = "*"
spirv-std-macros = "*"
spirv-std-types = "*"

[build-dependencies]
spirv-builder = "0.9"
